### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by szimek** [DustinJackson/html-webpack-inline-source-plugin#57] opened 2018-12-04 20:54 UTC
Hi! When I try to build my project using v1.0.0-beta.2 of this plugin, html-webpack-plugin v4.0.0-beta.4 and webpack v4.27.0, I'm getting the following error:
```
  TypeError: Cannot read property 'source' of undefined
  - index.js:53 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
    [web-service-main]/[html-webpack-inline-source-plugin]/index.js:53:22

  - index.js:122 HtmlWebpackInlineSourcePlugin.processTag
    [web-service-main]/[html-webpack-inline-source-plugin]/index.js:122:30

  - index.js:42
    [web-service-main]/[html-webpack-inline-source-plugin]/index.js:42:24

  - Array.forEach

  - index.js:41 HtmlWebpackInlineSourcePlugin.processTags
    [web-service-main]/[html-webpack-inline-source-plugin]/index.js:41:23

  - index.js:25 self.htmlWebpackPlugin.getHooks.alterAssetTagGroups.tapAsync
    [web-service-main]/[html-webpack-inline-source-plugin]/index.js:25:27

  - new Promise

  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [web-service-main]/[tapable]/lib/Hook.js:154:20

  - index.js:237 assetsPromise.then.then
    [web-service-main]/[html-webpack-plugin]/index.js:237:79
```

It looks like something is wrong with looking up assets. I'm using multiple entries and I've got multiple calls to html-webpack-plugin - I'm generating separate `index.html` for each language that we support.

The keys in `compilation.assets` are e.g.:
```
'assets/main/css/pt.2c4059d6.chunk.css',
'assets/main/css/ru.2c4059d6.chunk.css',
'assets/main/css/tr.2c4059d6.chunk.css',
```

Taking `'assets/main/css/tr.2c4059d6.chunk.css'` as an example, when this plugin is disabled, the generated `link` tag looks like this:
```
<link href="/assets/main/css/tr.2c4059d6.chunk.css" rel="stylesheet">
```
When this plugin is enabled, in the `processTag` method:
* `publicUrlPrefix` has value of `'/'`
* `filename` has value of `tr/index.html`
* `assetUrl` has initially the correct value of `'assets/main/css/tr.2c4059d6.chunk.css'`
* but later it's modified to `'tr//assets/main/css/tr.2c4059d6.chunk.css'`
* `assetName` has value of `Users/.../web-service-main/tr/assets/main/css/tr.2c4059d6.chunk.css`. 

Thus, the check `if (processedKey === assetName)` in `getAssetByName` function always fails and the function returns `undefined` instead of an asset.

If I remove this code:
```js
// if filename is in subfolder, assetUrl should be prepended folder path
if (path.basename(filename) !== filename) {
  assetUrl = path.dirname(filename) + '/' + assetUrl;
}
```
it seems to work correctly.

**Comment by itsnotatbug** [comment] 2018-12-05 15:35
Can you specify which version? When looking back at this later, it would be helpful to know the exact version since it will most likely be updated later on.

**Comment by andrevinsky** [comment] 2018-12-19 22:38
I, too, have the variation of this error.

I am using:
```
    "webpack": "^4.27.1",
    "html-webpack-inline-source-plugin": "0.0.10",
    "html-webpack-plugin": "^3.2.0",
```

The error is:
```
    ERROR in   TypeError: Cannot read property 'source' of undefined
      
      - index.js:56 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
        [framework]/[html-webpack-inline-source-plugin]/index.js:56:22
      
      - index.js:117 HtmlWebpackInlineSourcePlugin.processTag
        [framework]/[html-webpack-inline-source-plugin]/index.js:117:30
      
      - index.js:49 
        [framework]/[html-webpack-inline-source-plugin]/index.js:49:20
      
      - Array.forEach
      
      - index.js:48 HtmlWebpackInlineSourcePlugin.processTags
        [framework]/[html-webpack-inline-source-plugin]/index.js:48:19
      
      - index.js:29 
        [framework]/[html-webpack-inline-source-plugin]/index.js:29:27
      
      
      - new Promise
      
      
      - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
        [framework]/[tapable]/lib/Hook.js:154:20
      
      - index.js:673 
        [framework]/[html-webpack-plugin]/index.js:673:47
      
      - index.js:187 Promise.resolve.then.then.then.then.then.then.then.result
        [framework]/[html-webpack-plugin]/index.js:187:18
      
      - next_tick.js:68 process._tickCallback
        internal/process/next_tick.js:68:7
      
```

The plugin usage code:
```js
    plugins: [
      new HtmlWebpackPlugin({
        inject: true,
        inlineSource: '.(js)$', // embed all javascript and css inline,
        template: './src/comm.html',
        filename: `assets/${ COMM_HTML_NAME }`,
      }),
      new HtmlWebpackInlineSourcePlugin()
    ]
```

I believe this error is due to using `filename` prepended with a path (here, it is `assets/`). Whereas the output scripts are placed in the current (`.`) folder. I think the plugin looks for the scripts not in the place where they have been generated but rather in the place where this html gets finally. And there's nothing there - thus the error. Please confirm.

If the filename is specified without paths, i.e. `index.html`, all works fine.

**Comment by andrevinsky** [comment] 2018-12-19 22:58
Yup, a little investigation into the source code brings me this:
In, `index.js:116`:

```js
var assetName = path.posix.relative(publicUrlPrefix, assetUrl);
```

.. `assetName` may get prepended by `../` in case the `filename` (in `new HtmlWebpackPlugin({ ... filename: ``assets/${ COMM_HTML_NAME }`` ...}),`) is nested. Since the `compilation.assets` in the next line has only keys as simple filenames, not with paths, the resulting `var asset` gets `undefined`. Which, down the line, raises `TypeError: Cannot read property 'source' of undefined`.

I bet the simplest solution would be to strip off as many `../` as far the html output file is from the assets. I may be wrong and overlooking something. Leaving this up to you. @DustinJackson  @SovietFrontier, et al.

Proposed fix:
```js
var assetName = path.posix.relative(publicUrlPrefix, assetUrl).replace(/^(\.\.\/)+/g, '');
```

**Comment by shahzaibkhalid** [comment] 2018-12-23 19:16
I am also getting the same error.

**Comment by itsnotatbug** [comment] 2018-12-27 13:43
Are you guys getting this error simply by trying to compile? Everyone who posted saying you have the same error, can you show the compile options used as well in the same post?

**Comment by itsnotatbug** [comment] 2018-12-28 17:36
> I, too, have the variation of this error.
> 
> I am using:
> 
> ```
>     "webpack": "^4.27.1",
>     "html-webpack-inline-source-plugin": "0.0.10",
>     "html-webpack-plugin": "^3.2.0",
> ```

Hey @andrevinsky, @szimek  would you mind reverting to `v4.25.1` of `webpack` to see if it will fix your issue? I believe it might be a problem with not keeping up with the new code of `webpack` but I am not certain and I can't really test specific use cases that you guys have. Reverting back isn't the best case scenario but if it solves the problem, that would be a decent workaround until a fix is in place.

**Comment by tejash-jl** [comment] 2019-01-07 10:24
Is there any solution for this?
```
ERROR in   TypeError: Cannot read property 'source' of undefined

  - index.js:53 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
    [reacrh-frontend]/[html-webpack-inline-source-plugin]/index.js:53:22

  - index.js:118 HtmlWebpackInlineSourcePlugin.processTag
    [reacrh-frontend]/[html-webpack-inline-source-plugin]/index.js:118:30

  - index.js:42
    [reacrh-frontend]/[html-webpack-inline-source-plugin]/index.js:42:24

  - Array.forEach

  - index.js:41 HtmlWebpackInlineSourcePlugin.processTags
    [reacrh-frontend]/[html-webpack-inline-source-plugin]/index.js:41:23

  - index.js:25 self.htmlWebpackPlugin.getHooks.alterAssetTagGroups.tapAsync
    [reacrh-frontend]/[html-webpack-inline-source-plugin]/index.js:25:27


  - new Promise


  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [reacrh-frontend]/[tapable]/lib/Hook.js:154:20

  - index.js:237 assetsPromise.then.then
    [reacrh-frontend]/[html-webpack-plugin]/index.js:237:79


  - next_tick.js:189 process._tickCallback
    internal/process/next_tick.js:189:7
```

Current configuration,

> package.json
> ```
> ...
> "webpack": "^4.28.2",
> "html-webpack-plugin": "^4.0.0-beta.5",
> "html-webpack-inline-source-plugin": "^1.0.0-beta.2",
> ...
> ```

> compile options:
> ```
> optimization: {
> 	runtimeChunk: true,
> 	...
> },
> new HtmlWebpackPlugin({
> 	template: path.join(root_path, 'public/index.html'),
> 	filename: path.join(root_path, 'dist/index.html'),
> 	minify: {
> 		removeComments: true,
> 		collapseWhitespace: true,
> 		removeRedundantAttributes: true,
> 		useShortDoctype: true,
> 		removeEmptyAttributes: true,
> 		removeStyleLinkTypeAttributes: true,
> 		keepClosingSlash: true,
> 		minifyJS: true,
> 		minifyCSS: true,
> 		minifyURLs: true,
> 	},
> 	hash: true,
> 	inject: 'head',
> 	inlineSource: 'runtime~.+.js'
> }),
> new HtmlWebpackInlineSourcePlugin(HtmlWebpackPlugin),
> ```

**Comment by SovietFrontier** [comment] 2019-01-07 13:35
@tejashjl1020 please leave your compile options and `package.json` for webpack.....

**Comment by tejashjl1020** [comment] 2019-01-07 17:09
> @tejashjl1020 please leave your compile options and `package.json` for webpack.....

Im using,

> package.json
> ```
> ...
> "webpack": "^4.28.2",
> "html-webpack-plugin": "^4.0.0-beta.5",
> "html-webpack-inline-source-plugin": "^1.0.0-beta.2",
> ...
> ```

> compile options:
> ```
> optimization: {
> 	runtimeChunk: true,
> 	...
> },
> new HtmlWebpackPlugin({
> 	template: path.join(root_path, 'public/index.html'),
> 	filename: path.join(root_path, 'dist/index.html'),
> 	minify: {
> 		removeComments: true,
> 		collapseWhitespace: true,
> 		removeRedundantAttributes: true,
> 		useShortDoctype: true,
> 		removeEmptyAttributes: true,
> 		removeStyleLinkTypeAttributes: true,
> 		keepClosingSlash: true,
> 		minifyJS: true,
> 		minifyCSS: true,
> 		minifyURLs: true,
> 	},
> 	hash: true,
> 	inject: 'head',
> 	inlineSource: 'runtime~.+.js'
> }),
> new HtmlWebpackInlineSourcePlugin(HtmlWebpackPlugin),
> ```

**Comment by SovietFrontier** [comment] 2019-01-07 17:16
@tejashjl1020 please update your original post with this. Also, try setting your `webpack` back to `v4.25.1` and see if that works.

**Comment by itsnotatbug** [comment] 2019-01-07 18:46
@tejash-jl thanks! Did you try to set `webpack` to `v4.25.1`?

**Comment by tejash-jl** [comment] 2019-01-08 06:13
@SovietFrontier **NOPE**! I'm still getting the same error.

**Comment by dzotos** [comment] 2019-01-24 12:54
Hi, I'm getting the same error right after this https://github.com/DustinJackson/html-webpack-inline-source-plugin/issues/56

```
ERROR in   TypeError: Cannot read property 'source' of undefined

  - index.js:53 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
    [website]/[html-webpack-inline-source-plugin]/index.js:53:22

  - index.js:118 HtmlWebpackInlineSourcePlugin.processTag
    [website]/[html-webpack-inline-source-plugin]/index.js:118:30

  - index.js:42
    [website]/[html-webpack-inline-source-plugin]/index.js:42:24

  - Array.forEach

  - index.js:41 HtmlWebpackInlineSourcePlugin.processTags
    [website]/[html-webpack-inline-source-plugin]/index.js:41:23

  - index.js:25 self.htmlWebpackPlugin.getHooks.alterAssetTagGroups.tapAsync
    [website]/[html-webpack-inline-source-plugin]/index.js:25:27


  - new Promise


  - index.js:237 assetsPromise.then.then
    [website]/[html-webpack-plugin]/index.js:237:79
```

package.json

```
"webpack": "^4.28.4",
"html-webpack-plugin": "^4.0.0-beta.5",
"html-webpack-inline-source-plugin": "^1.0.0-beta.2",
```

**Comment by nschubach** [comment] 2019-02-19 21:24
@andrevinsky : That patch worked for me, but I think it's probably a "bad solution" to the problem.  The problem as I see it is that the plugin needs to find out what the context of the particular plugin being inlined is.  That's how the browser would treat that source and path.resolve() it from there.  I'm not an expert on webpack plugins by any measure, but the past hour of me tracing this down to the same location tells me that the path.posix.relative path is the relative path to the root of the project and not the root of the html file (and treating it as such is probably not right since the dev/browser will assume that the src is relative to the HTML file being inlined...)  Make sense?

**Comment by itsnotatbug** [comment] 2019-02-20 16:34
If you guys want to get in on this, add to this `pull request` #62

**Comment by rayking** [comment] 2019-03-29 09:43
> If the filename is specified without paths, i.e. `index.html`, all works fine.

keep filename without paths,and set css js path at rules:

  {
                    test: /\.(png|jp(e*)g|svg)$/,  
                    use: [{
                        loader: 'url-loader',
                        options: { 
                            limit: 8000, // Convert images < 8kb to base64 strings
                            name: 'images/[hash]-[name].[ext]'
                        } 
                    }]
                }

**Comment by itsnotatbug** [comment] 2019-03-29 12:42
> > If the filename is specified without paths, i.e. `index.html`, all works fine.
> 
> keep filename without paths,and set css js path at rules:
> 
> {
> test: /.(png|jp(e*)g|svg)$/,
> use: [{
> loader: 'url-loader',
> options: {
> limit: 8000, // Convert images < 8kb to base64 strings
> name: 'images/[hash]-[name].[ext]'
> }
> }]
> }

@rayking can you edit your reply with code blocks.

**Comment by dartandrevinsky** [comment] 2019-05-28 10:53
> > I, too, have the variation of this error.
> > I am using:
> > ```
> >     "webpack": "^4.27.1",
> >     "html-webpack-inline-source-plugin": "0.0.10",
> >     "html-webpack-plugin": "^3.2.0",
> > ```
> 
> Hey @andrevinsky, @szimek would you mind reverting to `v4.25.1` of `webpack` to see if it will fix your issue? I believe it might be a problem with not keeping up with the new code of `webpack` but I am not certain and I can't really test specific use cases that you guys have. Reverting back isn't the best case scenario but if it solves the problem, that would be a decent workaround until a fix is in place.

@SovietFrontier, the error stays:

```txt
    
    ERROR in   TypeError: Cannot read property 'source' of undefined
      
      - index.js:56 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
        [framework]/[html-webpack-inline-source-plugin]/index.js:56:22
      
      - index.js:117 HtmlWebpackInlineSourcePlugin.processTag
        [framework]/[html-webpack-inline-source-plugin]/index.js:117:30
      
      - index.js:49 
        [framework]/[html-webpack-inline-source-plugin]/index.js:49:20
      
      - Array.forEach
      
      - index.js:48 HtmlWebpackInlineSourcePlugin.processTags
        [framework]/[html-webpack-inline-source-plugin]/index.js:48:19
      
      - index.js:29 
        [framework]/[html-webpack-inline-source-plugin]/index.js:29:27
      
      
      - new Promise
      
      
      - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
        [framework]/[tapable]/lib/Hook.js:154:20
      
      - index.js:673 
        [framework]/[html-webpack-plugin]/index.js:673:47
      
      - index.js:187 Promise.resolve.then.then.then.then.then.then.then.result
        [framework]/[html-webpack-plugin]/index.js:187:18
      
    
    Child html-webpack-plugin for "resources/js/framework-comm.html":
         1 asset
        Entrypoint undefined = resources/js/framework-comm.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/comm.html 305 bytes {0} [built]
```

**Comment by itsnotatbug** [comment] 2019-05-28 12:42
@dartandrevinsky alas it is probably a little bit of both. I have to use `beta v3` so I don't have issues. I don't know when we will get this fixed. Thank you for trying though.

**Comment by PhysRex** [comment] 2019-07-17 14:18
I'm having the same issue, but couldn't get a solve when using the beta version

**Comment by Juraj-Masiar** [comment] 2019-08-23 08:31
So if I understand this correctly, the problem is with the multi-entry setup, right?
And there is no workaround, right?

**Comment by shin-hase** [comment] 2019-12-11 02:12
```
    "webpack": "^4.41.2",
    "html-webpack-inline-source-plugin": "0.0.10",
    "html-webpack-plugin": "^3.2.0",
```

```
	entry: {
		"ios/js/main": "./src/index.js",
		"android/js/main": "./src/index.js"
	},
	plugins: [
		new CleanWebpackPlugin(),
		new HtmlWebpackPlugin({
			template: "./src/b.html",
			chunks: ['ios/js/main'],
			inlineSource: '.(js|css)$',
			filename: "./ios/b.html"
		}),
		new HtmlWebpackPlugin({
			template: "./src/b.html",
			chunks: ['android/js/main'],
			inlineSource: '.(js|css)$',
			filename: "./android/b.html"
		}),
        new HtmlWebpackInlineSourcePlugin(),
	],
	output: {
		path: path.resolve(__dirname, OUTPUT_DIR),
		filename: '[name].js',
	},
```

```
ERROR in   TypeError: Cannot read property 'source' of undefined
  
  - index.js:56 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
    [b_html]/[html-webpack-inline-source-plugin]/index.js:56:22
  
  - index.js:117 HtmlWebpackInlineSourcePlugin.processTag
    [b_html]/[html-webpack-inline-source-plugin]/index.js:117:30
  
  - index.js:49 
    [b_html]/[html-webpack-inline-source-plugin]/index.js:49:20
  
  - Array.forEach
  
  - index.js:48 HtmlWebpackInlineSourcePlugin.processTags
    [b_html]/[html-webpack-inline-source-plugin]/index.js:48:19
  
  - index.js:29 
    [b_html]/[html-webpack-inline-source-plugin]/index.js:29:27
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [b_html]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 promisedApplyPluginsAsyncWaterfall
    [b_html]/[html-webpack-plugin]/index.js:673:47
  
  - index.js:187 
    [b_html]/[html-webpack-plugin]/index.js:187:18
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
```

**Comment by wmaca** [comment] 2020-02-05 16:00
In case anyone is wondering, in my specific multi-entry setup, the plugin is unable to find the tag href/src value in Webpack's asset list due to its inability to properly transform the href/src into a valid asset key.

To workaround this, it was enough to set a `publicPath` for Webpack's configuration (not the plugin's), so it could properly find the asset.

In my case, I had multiple links with href similar to  `../some/file.css`. When I added the `publicPath` as `/`, it became `/some/file.css` in my HTML, and the plugin was able to resolve it as the asset `some/file.css` (note there is no `/` in the beginning).

I hope this can be useful to anyone facing the same problem.

**Comment by danierlr** [comment] 2020-03-23 12:46
I have the same problem.

Here everything works:
```
    plugins: [
        new HtmlWebpackPlugin({
            filename: 'index.html',
            inlineSource: '.(js|css)$',
        }),
        new HtmlWebpackInlineSourcePlugin()
    ],
```

Here the error same as mentioned above occurs:
```
    plugins: [
        new HtmlWebpackPlugin({
            filename: 'something/index.html',
            inlineSource: '.(js|css)$',
        }),
        new HtmlWebpackInlineSourcePlugin()
    ],
```
Without HtmlWebpackInlineSourcePlugin everything works in both cases

**Comment by aczekajski** [comment] 2020-03-24 12:29
I had the same error. Downgrading webpack from `4.42.1` to `4.28.4` helped.

**Comment by aczekajski** [comment] 2020-03-24 12:47
I had the same error. For me, it's a difference between having `publicPath: '/'` in `output` part of webpack config or not having it. The error is thrown when I don't set `publicPath`.

**Closed as completed** 2020-03-31 23:51 UTC
Labels: bug

**Comment by njerschow** [comment] 2021-10-20 01:49
life saver @aczekajski
